### ISSUE TITLE
Script tag are not escaped and are evaluated when the message is displayed

### ISSUE THREAD

**Issue by leonard-IMBERT** [xvw/muhokama#31]
# Problem
The `<script>` tags need to be escaped when displayed to user or `<` and `>` characters should be html encoded  (`&#60;` and `&#62;` respectively).

Right now we can execute arbitrary code client side by injecting javascript through the messaging system.
# How to reproduce
For testing purpose, I use a local build

Before:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9348976/190244113-3d4df43b-4cb0-4f39-b735-9f9c0e5d3d54.png">
After:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9348976/190244240-642f1634-6e4e-4376-b9eb-7da194ad1e09.png">

I'll try push a PR to fix it but I'm not fluent in O'Caml so it might take a bit.

**Comment by gr-im** [comment]
Phew, that's bloody boring! I was sure that all the special characters had escaped. As a funny note, the Markdown specification for HTML is surprisingly vague. I'll look into it as soon as possible.

**Comment by leonard-IMBERT** [comment]
Funny, usernames seems to be correctly escaped

<img width="494" alt="image" src="https://user-images.githubusercontent.com/9348976/190251083-b73cd860-24d9-4bc8-9d42-d62e2878e25e.png">

**Comment by leonard-IMBERT** [comment]
After a few test, it seems for now that just the starting message of the topic and the reply are affected by the injection

**Comment by leonard-IMBERT** [comment]
I did not tried all the XSS vulnerabilities but here is a list of some of the weird thing we should look out:

https://cheatsheetseries.owasp.org/cheatsheets/XSS_Filter_Evasion_Cheat_Sheet.html

**Comment by gr-im** [comment]
Thanks for the report! 
I know how to fix that (and I'll do that soon as possible).
