### ISSUE TITLE
Datetime is not properly handled

### ISSUE THREAD

**Issue by xvw** [xvw/muhokama#61]
Since the time change, messages are posted one hour in the future. lol

**Comment by leonard-IMBERT** [comment]
Multiple ways to handle this:
 - Let the user specify it's time zone so we can adjust the publishing time
   - Need to add a field in the user profile
 - Show the date in UTC+1 and specify it in the display
 - Maybe if you know a way to fetch the timezone of a user by it's http request but not sure it's possible without javascript
Any preference ?

From what I've seen, the issue come from [this line](https://github.com/xvw/muhokama/blob/c6f4dbe0459d9dc5f9fb9921a05a3bba93a06ce7/app/templates/util.ml#L19) where the timezone is hardcoded (3600 * 2 -> UTC+2) whereas with the time change, France is now in UTC+1

**Comment by xvw** [comment]
Thanks a lot for the long run and the fix @leonard-IMBERT
