### ISSUE TITLE
Error: Missing fields on attempt to launch the app

### ISSUE THREAD

**Issue by lubegasimon** [xvw/muhokama#70]
I am trying to launch the app after following the `README.md` closing, but I am getting an error --
```
dune exec ./bin/muhokama.exe -- server.launch
[ERROR]Error.Invald_object { name = "env"; errors = Error.Field (Missing { name = 
       "POSTGRESQL_ADDON_PASSWORD"})
       Error.Field (Missing { name = "POSTGRESQL_ADDON_USER"})
       Error.Field (Missing { name = "POSTGRESQL_ADDON_DB"})
       Error.Field (Missing { name = "POSTGRESQL_ADDON_PORT"})
       Error.Field (Missing { name = "POSTGRESQL_ADDON_HOST"}) }
```
even after adding a `.env` file with contents (for example) --
```
POSTGRESQL_ADDON_HOST=localhost
POSTGRESQL_ADDON_PORT=5432
POSTGRESQL_ADDON_DB=muhokama_dev
POSTGRESQL_ADDON_USER=muhokama
POSTGRESQL_ADDON_PASSWORD=muhokama
LOG_LEVEL=debug
POSTGRESQL_ADDON_CONNECTION_POOL=5
```

Not sure what I could be missing!

_**system specifics:**_
```
Mac OS Ventura 13.5.2
OCaml version : 5.0.0
```

**Comment by xvw** [comment]
Maybe a naïve question but do you have `source .env` ?

**Comment by lubegasimon** [comment]
> Maybe a naïve question but do you have `source .env` ?

I think I am seeing `source .env` for the first time, I have used just `.env` before

**Comment by aguillon** [comment]
The muhokama binary does not try to read `.env` automatically (as you would have e.g. in Python with `loadenv()`), you have to load it before running the binary so that the environment variables are properly loaded. That's what `source .env` does.

**Comment by xvw** [comment]
Exactly. It could be forced, but I have to admit I like the idea of the user (or OPS) being free to choose how they provision environment variables. If you think it's an obvious improvement, we could potentially propose a fix :)

**Comment by lubegasimon** [comment]
> The muhokama binary does not try to read `.env` automatically (as you would have e.g. in Python with `loadenv()`), you have to load it before running the binary so that the environment variables are properly loaded. That's what `source .env` does.

Thank you, it now runs!

**Comment by lubegasimon** [comment]
> Exactly. It could be forced, but I have to admit I like the idea of the user (or OPS) being free to choose how they provision environment variables. If you think it's an obvious improvement, we could potentially propose a fix :)

I have no strong reasons for it being forced, perhaps just documenting the `source .env` somewhere in the `README.md`

**Comment by lubegasimon** [comment]
> ... perhaps just documenting the source .env somewhere in the README.md

Do you want that?
